View
Masouma864/Blog-Application pull request #2
Opened 2023-02-04 11:23 UTC by Masouma864

Use preprocessed HTML file with embedded Ruby code.
Use layouts and templates for shared content.

2023-02-04 14:15 UTC, Deepakdanger requested changes
Hi @Masouma864 , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
- [ ] While creating the Post there is one error ` undefined method Title for #<Post id: nil, title: "woo", text: "This is my first post", comment_counter: 5, like_counter: 2, created_at: nil, updated_at: nil, user_id: 1>`. There is typo error in post-title validation. Kindly fix it.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-04 14:15 UTC, Deepakdanger commented on app/controllers/users_controller.rb
> +  end
- [ ] Kindly provide here the particular user, not the all user.for ex:
```
def show
  @user = User.find(params[:id])
end
```

2023-02-04 14:15 UTC, Deepakdanger commented on app/views/users/show.html.erb
> +  <% end %>
- [ ] Here I am getting this error, Kindly resolve this.
![Screenshot from 2023-02-04 19-38-14](https://user-images.githubusercontent.com/26767383/216772084-3eca7da5-47e0-4ca9-8b03-dcb87648bd01.png)

2023-02-06 13:23 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Masouma864,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-06 13:23 UTC, Omar-Muhamad commented on app/views/posts/index.html.erb
> +  <% end %>
- [ ] You rendered the `post-card` partial here, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.), Please use the `recent_comments` method you created in the post model to render the most recent 5 comments only here in `posts index` view.

2023-02-06 13:23 UTC, Omar-Muhamad commented on app/views/posts/show.html.erb
> +</div>
- [ ] Great job using partials here.

2023-02-06 13:23 UTC, Omar-Muhamad commented on app/views/users/index.html.erb
> +      <% end %>
- [ ] Great job using partials here.

2023-02-06 14:34 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Masouma864, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and organized code
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-06 16:35 UTC, merged